version: '3'

services:
  redis:
    image: redis:alpine
    environment:
      - DOMAIN_NAME=redis.${BASEHOST:-magento.docker}
    network_mode: bridge

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-toor}
      - DOMAIN_NAME=mysql.${BASEHOST:-magento.docker}
    command: --innodb-doublewrite=0
    network_mode: bridge

  mailcatcher:
    image: mailhog/mailhog
    environment:
      - VIRTUAL_HOST=mailcatcher.${BASEHOST:-magento.docker}
      - VIRTUAL_PORT=8025
    network_mode: bridge

  application:
    image: dockerwest/php-magento${MAGENTOVERSION}:${PHPVERSION:-7.0}
    environment:
      - C_UID=${C_UID:-1000}
      - C_GID=${G_UID:-1000}
      - DEVELOPMENT=${DEVELOPMENT:-1}
    volumes:
      - ${APPLICATION:-../magento}:/phpapp
    links:
      - mysql
      - redis
      - mailcatcher
    network_mode: bridge

  nginx:
    image: dockerwest/nginx-magento${MAGENTOVERSION}:${NGINXVERSION:-stable}
    environment:
      - VIRTUAL_HOST=${BASEHOST:-magento.docker},${EXTRAHOSTS}
      - VIRTUAL_PORT=80
    volumes:
      - ${APPLICATION:-../magento}:/phpapp
    links:
      - application
    network_mode: bridge

